force-app/main/default/objects/Credential_detail__c/Credential_detail__c.object-meta.xml
<CustomObject>
    <label>Credential_detail</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Credential_detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credential_details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Credential_detail__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credential_detail__c/fields/my_Credential__c.field-meta.xml
<CustomField>
    <fullName>my_Credential__c</fullName>
    <label>my-Credential</label>
    <referenceTo>my_Credential__c</referenceTo>
    <relationshipLabel>Credential_details</relationshipLabel>
    <relationshipName>Credential_details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Credential_detail__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>Password</description>
    <label>Password</label>
    <length>50</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Credential_detail__c/fields/Redirect_URL__c.field-meta.xml
<CustomField>
    <fullName>Redirect_URL__c</fullName>
    <label>Redirect_URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credential_detail__c/fields/Security_answer__c.field-meta.xml
<CustomField>
    <fullName>Security_answer__c</fullName>
    <label>Security answer</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Credential_detail__c/fields/Security_question__c.field-meta.xml
<CustomField>
    <fullName>Security_question__c</fullName>
    <label>Security question</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Credential_detail__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Username for site</description>
    <label>Username</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/my_Credential__c/my_Credential__c.object-meta.xml
<CustomObject>
    <label>my-Credential</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>my-Credential Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>my-Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/my_Credential__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Cred_MainControllerTest.cls
@isTest
private class Cred_MainControllerTest {

    @testSetup 
    public static void setUpData()
    {
    }
    static testMethod void testPositiveNegative_Cred() {
       	//No data
        Cred_DataWrappers.Cred_ResultWrapper result = Cred_MainController.getCredentialData();
        
        //Data
        my_Credential__c my_cred = new my_Credential__c();
        my_cred.Category__c = 'Personal';
        insert my_cred;
                
        Credential_detail__c cdObj = new Credential_detail__c();
        	cdObj.my_Credential__c = my_cred.Id;
        	cdObj.Category__c = 'Personal';
            cdObj.Title__c = 'Facebook';
            cdObj.Redirect_URL__c = 'https://www.facebook.com';
            cdObj.Username__c = 'test@gmail.com';
            cdObj.Password__c = 'Test12304';
            cdObj.Email__c = 'test@gmail.com';
            cdObj.Mobile__c = '9876543210';
            cdObj.Security_question__c = 'Pet Name';
            cdObj.Security_answer__c = 'Maggi';
            cdObj.Comments__c = 'test';
        insert cdObj;
        
        Cred_DataWrappers.Cred_ResultWrapper resultCD = Cred_MainController.getCredentialData();
        system.debug('test:'+ resultCD);
        system.assert(resultCD != null);
        
        Cred_DataWrappers.Options op = new Cred_DataWrappers.Options();
        op.recId = my_cred.Id;
        op.Text = my_cred.Category__c;
        
        Cred_DataWrappers.CDWrapper Cred_DetailObject = new Cred_DataWrappers.CDWrapper();
        Cred_DetailObject.Category = op;
        Cred_DetailObject.Title = 'Gmail';
        Cred_DetailObject.Redirect_URL = 'https://www.gmail.com';
        Cred_DetailObject.Username = 'test-me@gmail.com';
        Cred_DetailObject.Password = 'test1234';
        Cred_DetailObject.Email = 'test@gmail.com';
        Cred_DetailObject.Mobile = '9876543210';
        Cred_DetailObject.Security_question = 'test';
        Cred_DetailObject.Security_answer ='test';
        Cred_DetailObject.Comments ='test';
        String str = JSON.serialize(Cred_DetailObject);
        
        //create new cd
        Cred_DataWrappers.Cred_ResultWrapper resultCreateNew = Cred_MainController.UpsertCredentialDetail(str, 'Create');
        system.assert(resultCreateNew != null);
        
        //create new cd with new category
        op.recId = '';
        op.Text = 'Other';
        resultCreateNew = Cred_MainController.UpsertCredentialDetail(str, 'Create');
        system.assert(resultCreateNew != null);
        
        //update
        Cred_DetailObject.Id = cdObj.Id;
        str = JSON.serialize(Cred_DetailObject);
        resultCreateNew = Cred_MainController.UpsertCredentialDetail(str, 'Update');
        system.assert(resultCreateNew != null);
        
        //delete
        resultCreateNew = Cred_MainController.UpsertCredentialDetail(str, 'Delete');
        system.assert(resultCreateNew != null);
    }
}